### PR TITLE
Minor Alkatra updates

### PR DESCRIPTION
**Pull request by yanone**
* Re-ordered some contours that were causing interpolation issues
* Removed outdated designer URL
* Updated license URLs from http to https

### CODE REVIEW

**Comment by suman51284** [comment]
Thanks for updating on the issues.

**Comment by suman51284** [comment]
Screenshot 2022-11-18 at 7 46 35 PM

Any idea why the vowel sign below the letter shows the white overlap?

**Comment by yanone** [comment]
No idea. Can you please specify the exact environment this is showing in ?

Older macOS versions are known to render overlaps with the gaps as shown, but I just checked in my own macOS 10.15 (which is affected), and it doesn't show.

**Comment by suman51284** [comment]
You are correct, I am using iOS 10.14 on this system.

**Comment by yanone** [comment]
Okay. There's possibly something that can be done about this (other than removing the overlaps, which is always possible), which is setting a specific flag for all affected glyphs that makes macOS render the glyphs with a different renderer, which will produce the correct results but will be slower to render. I've been wanting to understand this bit for a while now. I'll get back to you about that.

**Comment by suman51284** [comment]
I will try and look into such glyphs. This also makes me curious to look into the contextual alternates as well, whether certain combinations are replaced in a similar manner across iOS.

**Pull request merged**
